# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      
    working_directory: ~/BiopharmaScheduling

    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: merge to master
          command: |
            git fetch
            git config --global user.email "circle@kjankauskas.com"
            git config --global user.name "Circle CI"
            git checkout origin/master
            git merge --no-edit $CIRCLE_BRANCH
      
      - run:
          name: build base 
          command: |
            docker build -t biopharma-scheduling/base -f ./docker/base.docker .
        
      - run:
          name: build lab
          command: |
            docker build -t biopharma-scheduling/lab -f ./docker/lab.docker .

      - run:
          name: run C++ tests (undefined behaviour and memory leaks checks)
          command: |
            docker run -it --privileged biopharma-scheduling/lab bash -c "g++-8 -fsanitize=address,undefined -fno-sanitize-recover -fuse-ld=gold -g3 -std=c++14 -fopenmp -m64 tests/tests.cpp -o tests.out && ./tests.out"
    
      - run:
          name: run C++ tests (-O2 optimisations check)
          command: |
            docker run -it biopharma-scheduling/lab bash -c "g++-8 -O2 -std=c++14 -fopenmp -m64 tests/tests.cpp -o tests.out && ./tests.out"

      - run:
          name: run Python tests
          command: |
            docker run -it biopharma-scheduling/lab bash -c "cd tests && python tests.py"

      - store_artifacts:
          path: test-reports
          destination: test-reports